language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
      - env: SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} symfony/serializer:${SYMFONY_VERSION}

script:
  - phpunit --coverage-text
  - phantomjs Resources/js/run_jsunit.js Resources/js/router_test.html

notifications:
  email:
    - friendsofsymfony-dev@googlegroups.com
