language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.6
  - SYMFONY_VERSION=dev-master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require --dev symfony/framework-bundle:${SYMFONY_VERSION} symfony/serializer:${SYMFONY_VERSION}

notifications:
  email:
    - friendsofsymfony-dev@googlegroups.com
